import React from "react";



const users = [
  {
    id: 1,
    Nombre: "Tony Reichert",
    Categoria: "CEO",
    team: "Management",
    Estado: "activo",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    Nombre: "Zoey Lang",
    Categoria: "Tech Lead",
    team: "Development",
    Estado: "inactivo",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    Nombre: "Jane Fisher",
    Categoria: "Sr. Dev",
    team: "Development",
    Estado: "activo",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    Nombre: "William Howard",
    Categoria: "C.M.",
    team: "Marketing",
    Estado: "inactivo",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    Nombre: "Kristen Copper",
    Categoria: "S. Manager",
    team: "Sales",
    Estado: "activo",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    Nombre: "Brian Kim",
    Categoria: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    Estado: "activo",
  },
  {
    id: 7,
    Nombre: "Michael Hunt",
    Categoria: "Designer",
    team: "Design",
    Estado: "inactivo",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    Nombre: "Samantha Brooks",
    Categoria: "HR Manager",
    team: "HR",
    Estado: "activo",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    Nombre: "Frank Harrison",
    Categoria: "F. Manager",
    team: "Finance",
    Estado: "inactivo",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    Nombre: "Emma Adams",
    Categoria: "Ops Manager",
    team: "Operations",
    Estado: "activo",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    Nombre: "Brandon Stevens",
    Categoria: "Jr. Dev",
    team: "Development",
    Estado: "activo",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    Nombre: "Megan Richards",
    Categoria: "P. Manager",
    team: "Product",
    Estado: "inactivo",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    Nombre: "Oliver Scott",
    Categoria: "S. Manager",
    team: "Security",
    Estado: "activo",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    Nombre: "Grace Allen",
    Categoria: "M. Specialist",
    team: "Marketing",
    Estado: "activo",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    Nombre: "Noah Carter",
    Categoria: "IT Specialist",
    team: "I. Technology",
    Estado: "inactivo",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    Nombre: "Ava Perez",
    Categoria: "Manager",
    team: "Sales",
    Estado: "activo",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    Nombre: "Liam Johnson",
    Categoria: "Data Analyst",
    team: "Analysis",
    Estado: "activo",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    Nombre: "Sophia Taylor",
    Categoria: "QA Analyst",
    team: "Testing",
    Estado: "activo",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    Nombre: "Lucas Harris",
    Categoria: "Administrator",
    team: "Information Technology",
    Estado: "inactivo",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    Nombre: "Mia Robinson",
    Categoria: "Coordinator",
    team: "Operations",
    Estado: "activo",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export {users};
